# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CServices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wiprequest',
            name='c_method',
            field=models.CharField(choices=[('ROOM', 'room'), ('PHONE', 'phone'), ('ONLINE', 'online'), ('FOCUS', 'focus'), ('MIXED', 'mixed')], max_length=10),
        ),
    ]
