# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 01:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CServices', '0002_auto_20160705_2346'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('bid', models.FloatField(null=True)),
                ('length', models.IntegerField()),
                ('method', models.CharField(choices=[('ROOM', 'room'), ('PHONE', 'phone'), ('ONLINE', 'online'), ('FOCUS', 'focus'), ('MIXED', 'mixed')], max_length=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
