# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CServices', '0003_bidrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidrequest',
            name='IR',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='wiprequest',
            name='IR',
            field=models.IntegerField(null=True),
        ),
    ]
