# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 04:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CServices', '0004_auto_20160707_2121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wiprequest',
            old_name='c_method',
            new_name='method',
        ),
    ]
