# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CServices', '0005_auto_20160708_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidrequest',
            name='p_num',
            field=models.CharField(default='P999999', max_length=7),
        ),
        migrations.AddField(
            model_name='wiprequest',
            name='p_num',
            field=models.CharField(default='P999999', max_length=7),
        ),
    ]
