# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CServices', '0006_auto_20160710_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('ACTIVE', 'active'), ('COMPLETE', 'complete')], default='pending', max_length=10),
        ),
    ]
