# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CServices', '0007_bidrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidrequest',
            name='p_num',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='wiprequest',
            name='p_num',
            field=models.CharField(max_length=7),
        ),
    ]
