# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CServices', '0009_auto_20160711_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidrequest',
            name='bid_num',
            field=models.IntegerField(default=9999),
            preserve_default=False,
        ),
    ]
