# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 21:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CServices', '0010_bidrequest_bid_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bidrequest',
            name='IR',
        ),
        migrations.RemoveField(
            model_name='bidrequest',
            name='author',
        ),
        migrations.RemoveField(
            model_name='bidrequest',
            name='bid',
        ),
        migrations.RemoveField(
            model_name='bidrequest',
            name='bid_num',
        ),
        migrations.RemoveField(
            model_name='bidrequest',
            name='method',
        ),
        migrations.RemoveField(
            model_name='bidrequest',
            name='name',
        ),
        migrations.RemoveField(
            model_name='bidrequest',
            name='p_num',
        ),
        migrations.RemoveField(
            model_name='bidrequest',
            name='status',
        ),
    ]
