# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CServices', '0013_auto_20160714_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidoption',
            name='IR',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bidoption',
            name='bid',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='bidoption',
            name='length',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bidoption',
            name='method',
            field=models.CharField(choices=[('ROOM', 'room'), ('PHONE', 'phone'), ('ONLINE', 'online'), ('FOCUS', 'focus'), ('MIXED', 'mixed')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='bidoption',
            name='option',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bidoption',
            name='size',
            field=models.IntegerField(null=True),
        ),
    ]
