# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 01:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CServices', '0015_auto_20160714_2017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bidoption',
            old_name='bidreq',
            new_name='bidreqticket',
        ),
    ]
