# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CServices', '0016_auto_20160714_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assumptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_rate', models.IntegerField()),
                ('canadian_interviewing_rate', models.IntegerField()),
                ('american_interviewing_rate', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='bidoption',
            name='OB',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bidoption',
            name='OE',
            field=models.IntegerField(null=True),
        ),
    ]
